### ISSUE TITLE
write to a separate source map file from CLI

### ISSUE THREAD

**Issue by jonathanong** [MoOx/cssnext#107]
right now, you can only inline source maps. any way to allow separate source map files?

**Comment by MoOx** [comment]
https://github.com/cssnext/cssnext#map-default-depends-on-sourcemap

Is this enough for you ?

**Comment by jonathanong** [comment]
sorry. has to be more specific. i'm currently trying via CLI w/ the watcher. trying to avoid a custom node.js script :)

**Comment by MoOx** [comment]
Hum so I think I've done nothing yet. Maybe we should handle #73 to allow options from json ?

**Comment by MoOx** [comment]
Maybe you can check if `--config` can help you (you can provide a .js config)...
Hum it seems -map option doesn't exist yet. Should not be that hard to add around here https://github.com/cssnext/cssnext/blob/62aeafb32a8d8f50a655152486bad0bac65e25b4/bin/cssnext.js#L72
PRs are welcome :)

**Comment by jonathanong** [comment]
yeah was looking into the config. i can add ` .map` option to the config, but the source map is still not saved.

how would you want the option to look like? `--map <filename>`?

**Comment by MoOx** [comment]
--sourcemap is already inlining normally, so I guess if you use --map you must provide a filename. But yeah we can do that :) That should enable as well map entry in config file from wat I see in the code (I did not create the --config option).

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
