### ISSUE TITLE
Allow to run plugins before transformation (eg: plug a linter, run non-w3c like transformations)

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#149]
Ref https://github.com/postcss/postcss-import/issues/45
[stylelint](https://github.com/stylelint/stylelint) will be actively supported.

**Comment by Globegitter** [comment]
Looking forward to seeing that implemented :)

**Comment by magsout** [comment]
Good.I'm trying to use stylelint

**Comment by MoOx** [comment]
For now you should be able to use the [postcss-import `plugins` option](https://github.com/postcss/postcss-import#plugins) to lint all imported files. We still need to find a way to apply some plugins to all input (main input passed to postcss + imported files using the previously mentioned postcss-import option).

What about we create an option to do that? Here is some ideas for the name (most are shitty but you know, naming is not the easiest thing):

- pluginsOnEachInput
- pluginsForEachInputs
- onInputPlugins
- beforeProcessPlugins
- beforeProcessPlugins

Any smarter ideas are welcome :)

**Comment by kewah** [comment]
what about `beforeTransform` ? as you said it's before transformations

**Comment by MoOx** [comment]
Since it's a plugins array, maybe it should contains "plugins" in the option name.
`beforeTransformPlugins` is long, but clear.

**Comment by kewah** [comment]
:+1: 
`beforeTransform` sounds better for a callback but not for an array

**Comment by magsout** [comment]
`beforeTransformPlugins`

lgtm :+1:

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
