### ISSUE TITLE
Define cssnext as a postcss plugin internally

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#173]
We should follow cssnano api

- cssnext is defined as a postcss plugin (minor change)
- cssnext(options) return a postcss plugin (current behavior)
- cssnext(options).process(string) => result should be the implemented & promoted (new interface)
- maybe we can keep cssnext(string, options) api to avoid a major breaking change (current behavior) - not sure it's a good idea because postcss.plugin might add more change in the future. @ai any comment on that ?

This way, people might use directly cssnext (without braces) as a postcss plugin when https://github.com/postcss/postcss/issues/402 is fixed.

Not a big deal, but I think the reusable instance is a good idea.

Depending if the current api (string, options) can be kept, we might push this as a minor change or as a major bump (2.x)

**Comment by ben-eb** [comment]
I wouldn't recommend overloading your main exported method. Embrace breaking changes. :+1:

**Comment by ai** [comment]
Nice plan.

I think you should remove `cssnext(cssnext, opts)` API, because it makes code too complicated.

**Comment by MoOx** [comment]
You cannot say that `var css = cssnext(string, options)` is complicated versus `cssnext(options).process(string).css` or `cssnext(options).process(string).then(result) { result.css ...})`. That's not true ;)

**Comment by MoOx** [comment]
cssnext is now postcss-cssnext. cssnext is deprecated.
