### ISSUE TITLE
Clearly show what cssnext includes (autoprefixer, cssnano...)

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#180]
I am tired of notifying people about duplicate use + missuse of cssnext as a plugin. Ref https://github.com/eggsdesign/egg-incubator/issues/1

And #175 will not help, especially if people add autoprefixer after.

We should add something in the doc + automate some warnings. Ref https://github.com/postcss/postcss/issues/325 poke @ai @ben-eb

**Comment by ai** [comment]
This is question about perfomance or we have some big issue? I think to wait for other plugin packs to understand how people use packs. But I can force this task if we have bigger problem.

**Comment by MoOx** [comment]
It's not a perf issue, more a usage one. It's useless to add some plugins twice.
It's indeed an issue with plugins pack. For now there is not too many, but I think it's enough to decide that we should do something to prevent useless multiple passes...
I will think about that.
Maybe I will add a plugin in cssnext that will check the plugins list during the process() (so I can see all plugins used) in order to add some warnings to the end user. 
Yeah, I will do that. I will probably make a postcss plugin to detect and warn about multiple plugins. With an option to pass a whitelist for plugin that might be used more than once (rare use case). Maybe something like `postcss-detect-duplicate-plugins`.

**Comment by ai** [comment]
Yeap, `plugin.postcssPlugin` has added special for this cases.

**Comment by ben-eb** [comment]
@MoOx I've pretty much written it already, it is a core module inside cssnano. I could expand some of the logic, use the warnings API and extract it into a separate module if you like.

**Comment by MoOx** [comment]
Good idea. Please take in mind that I would like to be able to customize the message a little bit so I can produce something like 

> It seems you (or plugins that you are using) are including X more than once. This is not necessary.

**Comment by MoOx** [comment]
In your case I understand the idea to do that silently for some, but it does make sense to warn for most use cases.

**Comment by ben-eb** [comment]
I can make silent an off by default option. We could do some customisable string substitution, like `You are using %s more than once, which is unnecessary.`

**Comment by MoOx** [comment]
Yeah. Or more something like a template string (it's es6 below with template string + fat arrow function + destructuring for parameter)

```js
postcss(require("postcss-detect-duplicate-plugins")({
  warningTemplate: ({pluginName}) => `You are using ${pluginName} more than once, which is unnecessary`
})
```

ES 5 version


```js
postcss(require("postcss-detect-duplicate-plugins")({
  warningTemplate: function(params) {
    return "You are using " + params.pluginName + " more than once, which is unnecessary"
  }
})
```

**Comment by ben-eb** [comment]
What about this:

* `opts.silent (bool)`, don't show any warnings
* `opts.format (function)`, format function for each plugin message
* `opts.exclude (array)`, plugins that should not be deduplicated

And I like the name `postcss-filter-plugins`. :+1:

**Comment by MoOx** [comment]
lgtm except `format` name which seems unclear. I think we should go for something verbose like `(message|warning)|(Formatter|Template)`.

**Comment by ben-eb** [comment]
Would `opts.template` suffice?

**Comment by MoOx** [comment]
Why not. I like long name. I should code in Java.

**Comment by ben-eb** [comment]
@MoOx When warning the user, should we disable the affected plugin too?

**Comment by MoOx** [comment]
Why not, but I would prefer that user disable duplicate usage :)

**Comment by ben-eb** [comment]
Whichever you prefer, it's your use case. :smile:

**Comment by ben-eb** [comment]
@MoOx Done! https://github.com/postcss/postcss-filter-plugins

**Comment by MoOx** [comment]
Not relevant since postcss-cssnext now do not handle things that it should not (like import, cssnano etc).

**Comment by qm3ster** [comment]
So, to be clear:
1. postcss is the framework for plugins that work on stylesheet AST
2. cssnano is a distribution of postcss + some plugins already set up in an opinionated way, including notably autoprefixer. It also allows the passing of further plugins, and the passing of objects to the plugins within.
3. cssnext is distribution of postcss + some plugins already set up in an opinionated way, including notably autoprefixer, not as part of cssnano, and contains *all* of the plugins that cssnano does, enabled with the `compress` option?
Am I getting this right? 
Also, most options mentioned in the migration post are not on the usage page at the time of writing, including the #compress linked from this thread.

**Comment by MoOx** [comment]
postcss-cssnext is now just a collection of plugin and (except autoprefixer) there is no common plugin used with cssnano.
There is no default "opinionated" config. Autoprefixer is used in "normal" mode in cssnext and in "remove" mode in cssnano.

Like you said, old options that are not on the "usage" page have been removed. That's why there is a migration guide.

**Comment by ben-eb** [comment]
> (except autoprefixer) there is no common plugin used with cssnano.

& postcss-calc. 😄 

http://cssnano.co/optimisations/#calc
