### ISSUE TITLE
file in npm package is in year 2147

### ISSUE THREAD

**Issue by deevee** [MoOx/cssnext#182]
the following file: src/\_\_tests\_\_/fixtures/cli.watch-import-import.css has an incorrect date in the npm package of cssnext:
-rw-r--r--  1 me  wheel     7B 14 sep  2147 cli.watch-import-import.css

the file has a correct date when cloning the repo from github

**Comment by MoOx** [comment]
Haha that's weird. Is this a real issue or just a small detail ?
I am not sure why npm changes the dates...

**Comment by deevee** [comment]
small detail, but in case someone wants to make an archive containing this it will give an error saying that some files are in the future

**Comment by MoOx** [comment]
If you have a minute could you check with latest version (1.8.1)? Thanks in advance.

**Comment by deevee** [comment]
same problem

**Comment by MoOx** [comment]
Not relevant anymore (I guess). cssnext package is deprecated in favor of postcss-cssnext.
