### ISSUE TITLE
Messages can't be disabled in CLI

### ISSUE THREAD

**Issue by jeluard** [MoOx/cssnext#192]
It would be nice to be able to disable `messages` when using `cssnext` CLI. Also you might want to consider having the `browser` messages disabled by default as this is pretty intrusive and can't be hidden (I'm using a CSS DSL that generates some invalid CSS and always trigger the reporter).

**Comment by MoOx** [comment]
One workaround is to make a plugin that will remove some messages you don't want to see

```
// cssnext config
{
  plugins: [
    function(css, result) {
      for(var i=0; i < result.messages.length; i++) {
        if (result.messages[i].text == "THE WARNING YOU HATE") {
          result.messages = result.messages.slice(0,i).concat(result.messages.slice(i+1))
        }
    }
  ]
}
```

You can use a regex using  `...text.match(/regex/)` if messages are dynamic.

**Comment by jeluard** [comment]
Can I do that when using `cssnext` CLI? I'm using it as a shell command from a build tool without node support.

**Comment by MoOx** [comment]
I think CLI support a config file. Try `$ cssnext --help`.
Your file might be a .js and like this

```js
module.exports = {
  // cssnext config here
}
```

**Comment by jeluard** [comment]
It works perfect thanks!

For the record I used `cssnext -C config.js`

with `config.js`

```
module.exports = {
  messages: false
}
```

**Comment by MoOx** [comment]
postcss-cssnext do not handle messages anymore (cssnext is now postcss-cssnext. cssnext is deprecated.) See postcss-cssnext migration guide http://cssnext.io/postcss/
