### ISSUE TITLE
Add a note for url(...)  with css-modules in webpack.

### ISSUE THREAD

**Issue by boopathi** [MoOx/cssnext#199]
When you use cssnext with webpack's css-loader in module mode, `url(./file)` is transformed to `url(file)`. This is done by [postcss-url](https://github.com/postcss/postcss-url) included in cssnext. Because of this issue, if you use `url(./image.png)`, the css-loader?module gets it as `url(image.png)` and treats it as a module and searches in moduleDirectories rather than the relative path.

So, with css-loader module mode, I guess it is correct to use `{ url: false }` option in cssnext which is propagated to postcss-url. So can we add a note about this in this repo?

Related issues and discussions:

+ https://github.com/flipkart-incubator/phrontend-webpack/issues/8
+ https://gitter.im/postcss/postcss?at=55d5cd8280eb5af935921b1c
+ https://github.com/boopathi/css-loader-test-2/commit/835eb41255addd7c4506c4e6bfec9d2177cfb08f

**Comment by MoOx** [comment]
I think we should fix the issue in postcss-url, which should not change path like that.

**Comment by MoOx** [comment]
postcss-cssnext do not handle url anymore (cssnext is now postcss-cssnext. cssnext is deprecated.) See postcss-cssnext migration guide http://cssnext.io/postcss/
