### ISSUE TITLE
Add "input" and "output" option to config file

### ISSUE THREAD

**Issue by Gerhut** [MoOx/cssnext#207]
It will make npm script written more conveniently without specify input and output files in command line.

**Comment by MoOx** [comment]
Will try to add that the next time I will work on the cli.

**Comment by Gerhut** [comment]
Can I try implementing it and send a PR?

**Comment by MoOx** [comment]
Not a good idea. The cli will be rewritten at any moment (see #208 + wip of https://travis-ci.org/MoOx/cli-for-files) so please wait for this.

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
