### ISSUE TITLE
★ Convergence with PostCSS (make cssnext a preset, a la Babel 6.0)

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#208]
Following the [move of Babel 6.0](https://github.com/babel/babel/issues/2168), we should thinking to:
- [ ] [move part of cssnext interface into postcss core](https://github.com/postcss/postcss/issues/477)
- [ ] think about how to make cssnext more like an easy preset so people can choose what they want.
- [x] make [postcss-cssnext](https://github.com/cssnext/postcss-cssnext)

**Comment by awayken** [comment]
:cry: Reading this makes me sad, but as long as there is a neat and (fairly) easy way to convert existing cssnext sites to whatever is next for the project, then I'm up for it.

**Comment by awayken** [comment]
As a preset, would cssnext become something like postcss-cssnext?

**Comment by MoOx** [comment]
Be reassured, I won't kill the baby. Whatever solution is choosen, this will be easy to do for everyone, with a clear CHANGELOG on what to do.
I can see 2 things indeed:
- create postcss-cssnext and encourage the usage
- maybe keep "cssnext" package for a while that is basically what cssnext is today, probably with some changes under the hood, but not for end user.

That said, I think the most important thing will be to kill cssnext wrappers (gulp, grunt etc) and encourage postcss wrapper with the use of postcss-cssnext. It's not nice to have to maintain 2 similar things.
.postcssrc is required before any transition is planned, to help people having an easy transition without any pain.

**Comment by MoOx** [comment]
In short, you should be happy that we will work on something better for everyone ;)

**Comment by awayken** [comment]
That's good to hear. I still really love the ideas behind cssnext, so I'm glad there are the beginnings of a plan.

**Comment by magsout** [comment]
I think the idea of babel is interesting. It remains modular, eco-system is consistent and everything goes in the right direction. I like the idea. :+1:

**Comment by magsout** [comment]
Just a question. cssnext is not just a wrapper module, there is still a sense. How all this can be found in this version of postcss-cssnext?

**Comment by MoOx** [comment]
Something like postcss-cssnext will just be a bundle of cssnext "features" (no options). Some details about my idea here https://github.com/cssnext/cssnext/issues/202#issuecomment-138435421
I hope the other things that cssnext brings (easy interface, cli etc) will be backported to postcss, that the idea behind this issue. But I guess nobody is excited about it...

**Comment by magsout** [comment]
>But I guess nobody is excited about it...

Maybe because this idea is more philosophical. Currently cssnext works very well and make a awesome job. It is easy to install (npm) and to use (webpack, grunt, gulp). The subtlety of what you want to do isn't necessarily pertinante at beginning.

**Comment by MoOx** [comment]
[postcss-cssnext](https://github.com/cssnext/postcss-cssnext) is almost ready. That will help.

**Comment by codemakerlive** [comment]
Good work @MoOx, looking forward to it on npm

**Comment by ben-eb** [comment]
@MoOx Awesome. :+1:

**Comment by ChristopherBiscardi** [comment]
+1 We are running into a situation where we have cssnext running with a few other plugins and it looks like postcss-cssnext could help make our config a bit neater.

FWIW, the cssnext CLI has helped when debugging in the past, but it doesn't seem like a necessity.

.postcssrc is interesting, because it could mean configuring css for a static site generator [much like babel is configured](https://github.com/gatsbyjs/gatsby#configuring-babel), without the generator being opinionated beyond "processed with postcss".

**Comment by MoOx** [comment]
I plan to deprecate (and not update to cssnext v2) all runners:

-  cssnext-loader > postcss-loader + postcss-cssnext
- gulp-cssnext > gulp-postcss + postcss-cssnext
- grunt-cssnext > grunt-postcss+ postcss-cssnext
- fly-cssnext > fly-postcss + postcss-cssnext
- cssnextify > browserify-postcss + postcss-cssnext
- duo-cssnext > duo-postcss + postcss-cssnext
- cssnext-brunch > postcss-brunch + postcss-cssnext
- broccoli-cssnext > broccoli-postcss + postcss-cssnext
- cssnext-connect > postcss-middleware + postcss-cssnext

We should

- deprecate those packages on npm with a message + link on how to migrate with ease (I will try to offer a nice changelog so people might understand why to migrate to postcss-cssnext)
- move deprecated repos back to their owner or to postcss org ? (poke @ai)
- move cssnext to postcss org and delete the cssnext org ?

Not sure if it's necessary if the things about the org is necessary, but I found it would be stupid to keep a useless org, merging with postcss seems a better idea.

poke @ai and @cssnext/owners: sounds good to you? Any objection/comment ?
I would like to get a response from each runner owner please :)

**Comment by ai** [comment]
I move depreacted repos to my account to clean org https://github.com/ai/autoprefixer-core

**Comment by ai** [comment]
I think cssnext org is great for cssnext plugins

**Comment by MoOx** [comment]
There is not such thing as cssnext plugin and I plan to deprecate runners, so the org will be empty (just one repo)

**Comment by lionelB** [comment]
Sounds good to me. 
+1 for readme update to ensure a smooth transition

**Comment by magsout** [comment]
SGTM go 👍

**Comment by ai** [comment]
@MoOx in this case we can remove org :)

**Comment by shinnn** [comment]
Nice design :+1:

**Comment by watilde** [comment]
Yeah sounds good to me too!
+1

**Comment by MoOx** [comment]
I will wait for each runner owners to say "yes, I am ok, let's do this".

- [x] cssnext-loader (@MoOx)
- [x] gulp-cssnext (@MoOx)
- [x] grunt-cssnext (@MoOx)
- [x] duo-cssnext (@MoOx)
- [x] cssnext-brunch (@lionelb)
- [x] broccoli-cssnext (@shinnn)
- [x] cssnext-connect (@watilde)
- [ ] fly-cssnext (@bucaran or @drKraken)
- [ ] cssnextify (@ByteMuse)

**Comment by Swatinem** [comment]
[x] [https://github.com/Swatinem/gobble-cssnext](gobble-cssnext) (@Swatinem)
Sounds good. Waiting for your *link on how to migrate with ease*

**Comment by MoOx** [comment]
haha thanks for reporting this plugin as well, adding to the list

**Comment by Swatinem** [comment]
As a side note: There is [gobble-postcss](https://github.com/gobblejs/gobble-postcss) already, just need to know how to hook up the cssnext preset.

**Comment by MoOx** [comment]
poke @bucaran, @drKraken, @ByteMuse

**Comment by drKraken** [comment]
@MoOx  sounds good to me, lets do it! :) 
PS.Sorry for late response...

**Comment by MoOx** [comment]
I am working on this.
So for now working on https://github.com/postcss/postcss/issues/477 in order to make cssnext a simple plugin. Meanwhile, you can use postcss-cssnext. You can check about the difference here https://github.com/cssnext/postcss-cssnext#readme
Current postcss-cssnext repo will be deleted when postcss will have the parts of current cssnext that will be deleted from cssnext core (cli + config file). This way we will be able to provide an easy upgrade from current cssnext to postcss-cssnext usage with a simple config file. This repo will be renamed to postcss-cssnext and will be moved to postcss org.

**Comment by pensierinmusica** [comment]
@MoOx, what about the [npm package](https://www.npmjs.com/package/postcss-cssnext)? Will it be the same one throughout all changes and just be substituted with the new final repo once it's ready?

**Comment by MoOx** [comment]
Not sure yet, feel free to argue if we should keep "cssnext" as a postcss plugin or deprecate "cssnext" in favor of "postcss-cssnext". I am not sure what is the best to do. Maybe keeping the package as "postcss-cssnext"?
Please tell me what you think!

**Comment by pensierinmusica** [comment]
Mmm, according to what seems to be sort of a standard on [postcss docs](https://github.com/postcss/postcss#plugins) it looks like it depends on whether `cssnext` is to be considered as a "pack" (containing multiple plugins) or a single plugin.

If it's a "pack" then I'd say `cssnext` would fit fine, otherwise if it's a single plugin `postcss-cssnext` seems to be more in line with current naming conventions under the same `postcss` umbrella.

Thoughts?  :)

**Comment by MoOx** [comment]
I like what babel is doing. So in order to have cssnext as a preset, I think we should consider having postcss- in the name somewhere, especially if the code doesn't make any sense without postcss (which will be the case).

Here are some idea:
- postcss-pack-cssnext
- postcss-pack-w3c-{stage} (see #100 - where stage could be: proposal, wd, cr, rec : http://www.w3.org/2014/Process-20140801/#maturity-levels)

poke @ai and all the entire postcss community.

**Comment by cahnory** [comment]
postcss-next ?

**Comment by jonathanong** [comment]
@MoOx is `postcss-cssnext` safe to use right now?

**Comment by MoOx** [comment]
Yep. Just check the differences in postcss-cssnext readme.

**Comment by felixfbecker** [comment]
I just want cssNext to be to Sass/Less/Stylus what babel is to CoffeeScript/TypeScript/...

**Comment by MoOx** [comment]
@felixbecker this issue has been raised because babel (in 6.0) is becoming an engine like postcss that will do nothing by default (no transformation if no plugins added). If we want to follow babel footstep we should make cssnext a postcss preset (like babel-preset-es2015). That's why I mentionned a possible chane for the name. I still want mire input from cssnext users about that.

**Comment by felixfbecker** [comment]
Imo you must keep the name cssnext. Babel may be switching to a module approach, but they keep the name and everyone knows it stands for using next ES's features. CssNext has this association too. PostCSS doesnt.

**Comment by MoOx** [comment]
No that my point. Babel won't focus on ES future in it's core. That's a fact (just look at babel development branch atm).
That's why I am not sure how to adapt cssnext to be "just a preset" to enable the future of css and promote postcss as a main tool (in order to avoid duplicate effort for gulp/grunt/whatever runners/cli etc...).

**Comment by MoOx** [comment]
FYI, work is in progress to make official the deprecation of cssnext in favor of postcss-cssnext.
In order to keep the cssnext history/issues, I am merging back postcss-cssnext work in this repo, will delete postcss-cssnext repo and rename cssnext repo to postcss-cssnext.
The website will be update accordingly to this major change and provide a page with information on how to easily upgrade (and why). When this will be ready, I will close this issue in favor of https://github.com/postcss/postcss/issues/477

**Comment by MoOx** [comment]
After that all cssnext runners and interface will be deprecated on npm with a link in the deprecation message to point to the related (incoming) doc.

**Comment by MoOx** [comment]
Subscribers => https://github.com/MoOx/cssnext/issues/230#issuecomment-168530828

**Comment by MoOx** [comment]
Currently deprecating all runners I can and giving repo back to their owners.

**Comment by MoOx** [comment]
I can successfully deprecate the following:

- cssnext
- cssnext-loader
- gulp-cssnext
- grunt-cssnext
- duo-cssnext
- cssnext-brunch
- cssnext-connect
- broccoli-cssnext

But I wasn't able for this packages

- fly-cssnext
- gobble-cssnext
- cssnextify

@bucaran or @drKraken, please run this command ``npm deprecate fly-cssnext "cssnext is now postcss-cssnext. fly-cssnext is deprecated. Use fly-postcss instead. See postcss-cssnext migration guide http://cssnext.io/postcss/"``

@Swatinem, please run this command ``npm deprecate gobble-cssnext "cssnext is now postcss-cssnext. gobble-cssnext is deprecated. Use gobble-postcss instead. See postcss-cssnext migration guide http://cssnext.io/postcss/"``

@ByteMuse, please run this command ``npm deprecate cssnextify "cssnext is now postcss-cssnext. cssnextify is deprecated. Use browserify-postcss instead. See postcss-cssnext migration guide http://cssnext.io/postcss/"``

**Comment by MoOx** [comment]
I make transfert request to all original creators of the packages. Tell if I made something wrong.

**Comment by bucaran** [comment]
Hi @MoOx 

The amount of information is massive, do you have a FAQ or link to see a summary of what happened?

Thanks!

**Comment by MoOx** [comment]
It's very simple: http://cssnext.io/postcss/

**Comment by bucaran** [comment]
Thanks, the JavaScript scene is so exciting :laughing:

**Comment by MoOx** [comment]
It's alive.
