### ISSUE TITLE
Add postcss-initial

### ISSUE THREAD

**Issue by ai** [MoOx/cssnext#214]
I think we should add this plugin to cssnext https://github.com/maximkoretskiy/postcss-initial

It is `all: initial` polyfill. This property will return all inherited styles to base one.

This plugin is really amazing, because it can be used to create absolutly isolated widgets. Like we will use CSS Modules to isolate selectors and then `all: initial` to isolate pproperties.

**Comment by maximkoretskiy** [comment]
Just sent PR to postcss-cssnext 
https://github.com/cssnext/postcss-cssnext/pull/12

Waiting for cssnext version upgrade https://github.com/cssnext/cssnext/issues/202

**Comment by MoOx** [comment]
Released as postcss-cssnext 2.1.0, will close this when #202 is ok

**Comment by maximkoretskiy** [comment]
Now we waiting for https://github.com/cssnext/cssnext/issues/208

**Comment by maximkoretskiy** [comment]
:tired_face:

**Comment by MoOx** [comment]
What?

**Comment by ai** [comment]
@maximkoretskiy `postcss-cssnext` is already released and can be used.

**Comment by maximkoretskiy** [comment]
Yes, I know. But postcss-initial is not mentioned in official docs.

**Comment by MoOx** [comment]
Official doc are currently kind of outdated, like cssnext itself.
I need to take some times, I will probably do that before my conference (about PostCSS) at the end of the month, so be patient.
OR you can help in the appropriate issues. That's also a solution.

**Comment by maximkoretskiy** [comment]
ОК, I ll look around in project issues.

**Comment by MoOx** [comment]
Done in postcss-cssnext. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
