### ISSUE TITLE
Update pixrem dependency to v3.0.0 for rootValue

### ISSUE THREAD

**Issue by SammyM** [MoOx/cssnext#225]
Is it possible to update the pixrem dependency to version 3.0.0 so that the rootValue option can be used?

Reference: https://github.com/robwierzbowski/node-pixrem/issues/40

**Comment by MoOx** [comment]
See #208 for the reason of the blocker.

**Comment by MoOx** [comment]
Done in postcss-cssnext. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
