### ISSUE TITLE
⚠︎ Deprecate cssnext in favor or postcss-cssnext

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#230]
Following #202 and #208

**Comment by MoOx** [comment]
Please give your opinion about this comment https://github.com/cssnext/cssnext/issues/208#issuecomment-145007729
Meanwhile, you can use instead of using cssnext, please use the postcss runner of your choice with postcss-cssnext https://github.com/cssnext/postcss-cssnext

Here are the differences https://github.com/cssnext/postcss-cssnext#readme

**Comment by awayken** [comment]
My opinion is that I'm comfortable doing whatever you think is best, @MoOx. I don't have any experience with Babel and have very little experience with PostCSS in general, so I have no preference on the use of PostCSS packs or plugins or anything else that's been suggested.

I use the Gulp to process my cssnext so as long as we can provide even simple examples that show how to convert to the new usage, then that should work fine for me.

**Comment by ben-eb** [comment]
I like it, makes cssnext more of a focused plugin, should be easier to support with less internal dependencies.

**Comment by awayken** [comment]
@MoOx Do you have recommendations for when users of cssnext should start rewriting their build process to use postcss-cssnext instead? Do you feel like things are ready for people to transition, or is there still work to be done?

**Comment by MoOx** [comment]
Currently using postcss-cssnext is totally safe, you will just need to adjust your workflow to use postcss + some plugins instead of directly cssnext.
I think (in order to provide a good transition) we should only deprecate cssnext when we will have doc on how to upgrade for every kind of workflow (grunt, gulp etc) and I think handling this might help a lot https://github.com/postcss/postcss/issues/477 (because instructions will be almost the same for everyone).

**Comment by MoOx** [comment]
Subscribers, please take a look to this incoming merged PR if you want to start the transition today (before it came official, you can already try and migrate)

https://github.com/MoOx/cssnext/blob/c83d39aac5ee17f1c01d06406ec81259d6/docs/content/postcss.md

That might also help https://github.com/MoOx/cssnext/blob/c83d39aac5ee17f1c01d06406ec81259d6/CHANGELOG.md

Ref #238

**Comment by MoOx** [comment]
In progress. Will be done in an hour max.

**Comment by mohammadayoub96** [comment]
I think delete this repo. so beginners will not confuse.

**Comment by jonathantneal** [comment]
There is no repo to delete. This is the official repo for cssnext. The old npm package was deprecated. You can see it for yourself https://www.npmjs.com/package/cssnext

**Comment by MoOx** [comment]
Don't worry, I will take care of this issue and deprecated postcss-cssnext soon.
I just want to do this with the right amount of time to make this right. I will update the site etc with banners & shit. @jonathantneal did you plan a website or something for this plugin? Or nothing more than the README? (just to know)

**Comment by jonathantneal** [comment]
I think @mohammadayoub96 was talking about the npm package name, and I was clearing up the confusion. I wasn’t addressing the future of postcss-cssnext.

To answer your question: I would love to build a website, yes. The last week has given me limited time + 2 recent feature/plugin requests completed + 1 feature/plugin requests still pending + 2 plugins needing to be updated. 😄

**Comment by mohammadayoub96** [comment]
I asked this because i was confused to know about postCss, CssNext, cssNext-PostCss, Autoprefixers. Thats why i say this.
