### ISSUE TITLE
Outdated Autoprefixer

### ISSUE THREAD

**Issue by skinnyfoetusboy** [MoOx/cssnext#231]
When should we expect to see Autoprefixer upgraded to 6.0 in cssnext?

**Comment by magsout** [comment]
@skinnyfoetusboy https://github.com/cssnext/cssnext/issues/230 I guess never ?

**Comment by magsout** [comment]
@skinnyfoetusboy https://github.com/cssnext/postcss-cssnext with autoprefixer 6.0

**Comment by skinnyfoetusboy** [comment]
Damn.

**Comment by skinnyfoetusboy** [comment]
@MoOx Maybe you should update the README to reflect the change of direction you've chosen for cssnext?

**Comment by MoOx** [comment]
It will require some time to explain people how to migrate. This require some amount of time I am not ready to spend yet :/
I would like this issue https://github.com/postcss/postcss/issues/477 to be handled before in order to make a "generic" transition easier for everyone.

**Comment by MoOx** [comment]
Done in postcss-cssnext. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
