### ISSUE TITLE
sourcemap can't work

### ISSUE THREAD

**Issue by fsy0718** [MoOx/cssnext#237]
`Your current PostCSS version is 5.0.13, but postcss-color-function uses 4.1.16. Perhaps this is the source of the error below.`
  `events.js:141`
       `throw er; // Unhandled 'error' event`

**Comment by MoOx** [comment]
Please see postcss-cssnext and #230.

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
