### ISSUE TITLE
Generic config file

### ISSUE THREAD

**Issue by MoOx** [MoOx/cssnext#73]
Following #72

What about supporting these file:

- (.)?cssnext.json
- (.)?cssnext.yml
- .cssnextrc (json or yaml)
- (.)?cssnext.config.js (that exports config)

**Comment by hgl** [comment]
Do you mean a config file that the CLI will automatically look for (in cwd?) when it executes?

**Comment by MoOx** [comment]
Yep

**Comment by magsout** [comment]
`cssnext.json` Sounds good.

Any plan about that ?

**Comment by MoOx** [comment]
I don't plan to implement that in a near future. That being said, PRs are always welcome (note: maybe we should discuss a little bit on the implementation before pushing this)

**Comment by magsout** [comment]
This option interests me. I rather like to use a json configs. Especially I want to delete gulp on my workflow. We discuss on irc next week if you're available

**Comment by Nyalab** [comment]
.cssnextrc with a json syntax

**Comment by magsout** [comment]
@Nyalab 
why *rc ?

**Comment by MoOx** [comment]
if we support json, I guess we can easily support js too (trick: export a js object).

Do you think yml support is useless ?
I found yml easier to maintain than json (and it accept comments) but I think I will use JS anyway (especially to require shared variables).

**Comment by pascalduez** [comment]
`.cssnextrc` (json or yaml)

Just my too cents.

`.<projectname>rc` is a widely used convention: `.eslintrc`, `.jshintrc`, `.babelrc` ...

Supporting both JSON and YAML is neat, and a breeze using [js-yaml](https://github.com/nodeca/js-yaml).

One minor hitch though, syntax highlighting in editors with the .rc sheme.

**Comment by MoOx** [comment]
This will support js/json/yaml

**Comment by MoOx** [comment]
Do you think js support for the config (like webpack) is mandatory? 
I plan to rely on [rc](https://www.npmjs.com/package/rc) but for now this module only handle json/ini. Note that it's easy to add a parser (eg: yaml), so I guess trying to eval() the config might be doable. Not sure if that's a smart/secure idea.

**Comment by MoOx** [comment]
https://github.com/MoOx/rc-loader is ready.

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
