### ISSUE TITLE
Compile folder of .css files at once

### ISSUE THREAD

**Issue by voronianski** [MoOx/cssnext#93]
It will be handy to have such possibility, smth like:

```bash
cssnext --folder ./folder --output-folder ./output
```

**Comment by MoOx** [comment]
Maybe we can just accept a glob for the input filename ?
Like

```console
$ cssnext "folder/*.js" ./out/
```

Not sure if it's a good idea since some shell (eg: zsh) might resolve the glob as multiple filenames.

**Comment by MoOx** [comment]
Not relevant anymore. cssnext is now postcss-cssnext. cssnext is deprecated. See postcss-cssnext migration guide http://cssnext.io/postcss/
